# NOTE: update this with your service name
service: fdwa-backend

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  FoodDeliveryTable: ${self:custom.stage}-fdwa
  tableThroughputs:
    prod: 5
    default: 2
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

provider:
  profile: personal
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  environment:
    FoodDeliveryTable: ${self:custom.FoodDeliveryTable}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStream

      Resource:
        - "Fn::GetAtt": [ FoodDeliveryTable, Arn ]

functions:
  graphql:
    handler: src/graphql.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy

      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy

resources:
  #DynamoDB
  - ${file(resources/fdwa-table.yml)}
  #Cognito - User Pool
  - ${file(resources/cognito-user-pool.yml)}
  #Cognito - Identity pool
  - ${file(resources/cognito-identity-pool.yml)}
